// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtPLySzHBBhTbdQxARrMqMMTp_IjJq5Nc',
    appId: '1:364254636772:web:73b30f930c836db84c1af1',
    messagingSenderId: '364254636772',
    projectId: 'mumbaihacks-5687f',
    authDomain: 'mumbaihacks-5687f.firebaseapp.com',
    storageBucket: 'mumbaihacks-5687f.appspot.com',
    measurementId: 'G-17JMJ72PTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKDkAhkSXYRgXW0TD0hrnFjj_XtkdQQLg',
    appId: '1:364254636772:android:c46a30bb84b9f6974c1af1',
    messagingSenderId: '364254636772',
    projectId: 'mumbaihacks-5687f',
    storageBucket: 'mumbaihacks-5687f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-J5oCSTsPa4z_vNqKb2zEUXcQJ9wXmgc',
    appId: '1:364254636772:ios:1ad3db407179944b4c1af1',
    messagingSenderId: '364254636772',
    projectId: 'mumbaihacks-5687f',
    storageBucket: 'mumbaihacks-5687f.appspot.com',
    iosBundleId: 'com.example.mumbaihacks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-J5oCSTsPa4z_vNqKb2zEUXcQJ9wXmgc',
    appId: '1:364254636772:ios:1ad3db407179944b4c1af1',
    messagingSenderId: '364254636772',
    projectId: 'mumbaihacks-5687f',
    storageBucket: 'mumbaihacks-5687f.appspot.com',
    iosBundleId: 'com.example.mumbaihacks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtPLySzHBBhTbdQxARrMqMMTp_IjJq5Nc',
    appId: '1:364254636772:web:436db4b0557ae54a4c1af1',
    messagingSenderId: '364254636772',
    projectId: 'mumbaihacks-5687f',
    authDomain: 'mumbaihacks-5687f.firebaseapp.com',
    storageBucket: 'mumbaihacks-5687f.appspot.com',
    measurementId: 'G-LYEF1GFT15',
  );
}
